### ISSUE TITLE
Facing an unexpected issue while running the build command "ng build --aot --build-optimizer"

### ISSUE THREAD

**Issue by dinesh-tech1990** [apexcharts/ng-apexcharts#193]
I have been using the below version and my project was running fine.
"apexcharts": "^3.19.2",
"ng-apexcharts": "^1.2.0",

But for the last seven days, I am facing an unexpected issue while running the "ng build --aot --build-optimizer"
Error-
ERROR in : Unexpected value 'NgApexchartsModule in /var/lib/jenkins/workspace/build-dummy-project/dummy-project/node_modules/ng-apexcharts/lib/ng-apexcharts.module.d.ts' imported by the module 'DummyProjectModule' in /var/lib/jenkins/workspace/build-dummy-project/dummy-project/src/app/dummy-project/dummy-project.module.ts'. Please add a @NgModule annotation.
node_modules/ng-apexcharts/lib/chart/chart.component.d.ts(53,21): error TS2694: Namespace '"/var/lib/jenkins/workspace/build-dummy-project/dummy-project/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
node_modules/ng-apexcharts/lib/chart/chart.component.d.ts(54,21): error TS2694: Namespace '"/var/lib/jenkins/workspace/build-dummy-project/dummy-project/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
node_modules/ng-apexcharts/lib/ng-apexcharts.module.d.ts(9,21): error TS2694: Namespace '"/var/lib/jenkins/workspace/build-dummy-project/dummy-project/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
node_modules/ng-apexcharts/lib/ng-apexcharts.module.d.ts(10,21): error TS2694: Namespace '"/var/lib/jenkins/workspace/build-dummy-project/dummy-project/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.
node_modules/ng-apexcharts/lib/ng-apexcharts.module.d.ts(11,21): error TS2694: Namespace '"/var/lib/jenkins/workspace/build-dummy-project/dummy-project/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

**Request you to please provide the solution asap.**

**Comment by 9953542556** [comment]
I am also facing the issue since 2 days.

WARNING in Missing font family at 31370:8. Ignoring.
WARNING in Invalid font values at 41996:2. Ignoring.
ERROR in : Unexpected value 'NgApexchartsModule in /builds/regcomp/KY3P/ky3p-portals/kyv-master/kyv-webapp/kyv-webapp-ui/node_modules/ng-apexcharts/lib/ng-apexcharts.module.d.ts' imported by the module 'InviteModule in /builds/regcomp/KY3P/ky3p-portals/kyv-master/kyv-webapp/kyv-webapp-ui/libs/ui-kit/src/lib/components/invite/invite.module.ts'. Please add a @NgModule annotation.
WARNING in Invalid background value at 11738:18. Ignoring.
WARNING in Missing font family at 31530:8. Ignoring.
WARNING in Missing font family at 31542:8. Ignoring.
WARNING in Missing font family at 31781:8. Ignoring.
WARNING in Invalid font values at 42677:2. Ignoring.
WARNING in Invalid font values at 43070:2. Ignoring.
WARNING in Invalid font values at 45229:2. Ignoring.
ERROR in : Unexpected value 'NgApexchartsModule in /builds/regcomp/KY3P/ky3p-portals/kyv-master/kyv-webapp/kyv-webapp-ui/node_modules/ng-apexcharts/lib/ng-apexcharts.module.d.ts' imported by the module 'InviteModule in /builds/regcomp/KY3P/ky3p-portals/kyv-master/kyv-webapp/kyv-webapp-ui/libs/ui-kit/src/lib/components/invite/invite.module.ts'. Please add a @NgModule annotation.
Date: 2022-02-14T09:03:29.334Z
Hash: 42f238229cbda4121a56

**Comment by dinesh-tech1990** [comment]
>

**Comment by dinesh-tech1990** [comment]
@JackBatty98 and @9953542556
Could you please share the ng-apexcharts and angular version?

**Comment by 9953542556** [comment]
"apexcharts": "^3.27.2",
"ng-apexcharts": "^1.5.12",

Angular 7

**Comment by dinesh-tech1990** [comment]
@9953542556 ,
I have checked, The issue has occurred because of the version conflicting between ng-apexcharts and @angular/core packages.
So the solution is you have to downgrade the ng-apexcharts version or upgrade the angular project.

**Comment by T0BiD** [comment]
@dinesh-tech1990 
is there an ng-apexcharts version you recommend for Angular 7?

**Comment by dinesh-tech1990** [comment]
@T0BiD 
Could you please share the ng-apexcharts and angular version?
