### ISSUE TITLE
Dynamically load apexcharts

### ISSUE THREAD

**Issue by hc-codersatlas** [apexcharts/ng-apexcharts#26]
Hi, can the apexcharts js be dynamically / lazy loaded? It's a large file and not needed on all pages. Would be good if it can be loaded on demand just as required like a few other angular libs.

**Comment by djabif** [comment]
@hc-codersatlas I created a PR  https://github.com/apexcharts/ng-apexcharts/pull/29 to solve this issue.

**Comment by junedchhipa** [comment]
Thanks @djabif

**Comment by astone2014** [comment]
I am loading the `NgApexchartsModule` in a lazy module but it still appears in the main bundle.

Is the idea that the `apexcharts.js` file should be in the lazy module?

![image](https://user-images.githubusercontent.com/22425467/109902302-45894880-7c68-11eb-983b-ad91975f5412.png)

**Comment by exitlol** [comment]
I am facing the same issue as @astone2014 does I am only importing the module, but my bundle contains the whole common.js.
Is it because of the higher mentioned #29 MR? Since you import the whole thing it's gonna import everything from apexcharts w/o treeshaking unused stuff.
How can we fix this issue?
As you can see apexcharts is 25%!!!! of the whole bundle. It hurts on mobile especially.
![Képernyőkép 2021-04-08 142812](https://user-images.githubusercontent.com/36930188/114026568-ad8a0a80-9876-11eb-9350-c4d92a0f120f.png)

**Comment by jinman** [comment]
were you able to fix this this? or lazy load apex charts?
