### ISSUE TITLE
Warning In angular 10 

### ISSUE THREAD

**Issue by yeshwanthmn** [apexcharts/ng-apexcharts#92]
When I  start the angular 10 app I am getting below mentioned warning 
ng-apexcharts\__ivy_ngcc__fesm2015 g-apexcharts.js depends on 'apexcharts'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by IsaacSomething** [comment]
This issue can be removed by adding `"apexcharts"` to the `allowedCommonJsDependencies` in your `angular.json` file 

```
"architect": {
        "build": {
             "options": {
                  "allowedCommonJsDependencies":

```

**Comment by j-a-h-i-r** [comment]
@IsaacSomething, this will only suppress the warning and not actually fix the issue causing this warning.

**Comment by stefanolsenn** [comment]
That's because this lib is depending on the CommonJS module instead of the ESM (surprise)

I see that they changed the import from the ESM to the min version, and later removed the deep import to get rid of the ivy warning. See #79 
@junedchhipa Maybe you could clarify a bit on that decision? I would rather silence the deep import warning, than my bundle size increases.

**Comment by junedchhipa** [comment]
@stefanolsenn The ESM module caused issues in all libraries (react/vue/angular) because of the way it was generated.
I haven't found a fix for that and hence it was removed.

**Comment by stefanolsenn** [comment]
What issues are we talking about here?

**Comment by junedchhipa** [comment]
There is a 3rd party library called svg.js being bundled inside ESM.
So, instead of the main `ApexCharts` being exposed, `SVG` was exposed from the ESM module.

**Comment by stashaway** [comment]
Any news on this? Seems like the svg.js being exposed is an issue that could be solved. As Angular moves pretty fast, it would be great to not have optimization bailouts in the current versions.

**Comment by MNorgren** [comment]
Any updates on this? apexcharts is 25% of my apps bundle size.

**Comment by AmirSavand** [comment]
Any update on this? Is this a time-consuming bug to fix?

**Comment by muhammadtayab257** [comment]
in your angular.json file, you need to add

**Comment by muhammadtayab257** [comment]
![Screenshot 2022-07-26 135854](https://user-images.githubusercontent.com/60255376/180967275-ad354e39-73e9-4620-a90f-16c79a462396.png)

In your, angular.json(build > option ) file add these line 
 "allowedCommonJsDependencies": ["apexcharts"],

**Comment by AmirSavand** [comment]
@muhammadtayab257 That's just ignoring the warning.

**Comment by VitorBarleta** [comment]
Any update on this issue? I just updated from Angular 13 (everything was ok) to Angular 14 and this warning started to appear.

**Comment by rtpHarry** [comment]
Seeing this as well with Angular 16 :/

**Comment by jeroen1602** [comment]
I found that manually adding:

```JSON
"es2020": "dist/apexcharts.esm.js",
```

to the `package.json` of the `apexchart` package makes it so that the Angular compiler can find the correct ESM version.

So to get this fixed we would need to get this field added to the apexcharts library.

Here is the order that Angular uses to find the entry point in a package:
https://github.com/angular/angular-cli/blob/d6a34034d7489c09753090642ade4c606cd98ece/packages/angular/build/src/tools/esbuild/application-code-bundle.ts#L50
