### ISSUE TITLE
showSeries and hideSeries is not working properly

### ISSUE THREAD

**Issue by Napstergfr** [apexcharts/ng-apexcharts#95]
When i am calling hideSeries to hide some of the Series it's working but after that when i am trying to show a specific Series from them it's not working.

**Comment by rraut** [comment]
Facing same issue. Have you found any solution?

**Comment by junedchhipa** [comment]
Can you please specify the versions of `apexcharts` as well as `ng-apexcharts`?

**Comment by rraut** [comment]
Thanks for your support. My issue is sorted. Initially I was adding series into mount that's why on any change it was setting series back to visible. Now I am hiding it on update which sloves the first problem. But got obvious problem , when I click the legend it is still not showing me series as I am hiding it on update. Is there any hook which will allow me to check the name of clicked legend/ series inside updata

**Comment by rraut** [comment]
@junedchhipa Is it possible to get clicked legend's id inside update event of apex chart?

**Comment by Napstergfr** [comment]
I couldn't fix it I had to use ngx-charts that worked for me.

**Comment by Procisz** [comment]
Same issue here. Any solution, please?
resetSeries(), toggleSeries(), showSeries(), hideSeries() are not working properly by clicking in the chart or call it programatically.

When I hide one series in a multiplre area chart (woth 3 series), the whole chart become empty, and thats it...
